#!/usr/bin/env php
<?php

use App\Amounts\PrintAmount;
use App\Converters\Converter;
use App\CurrencyConverter;
use App\Quotations\JsonFile;

require('vendor/autoload.php');

if ($argc != 4)
    die("Enter tree parameters: 1 - the amount to be converted, 2 - the source currency, 3 - the destination currency\nex: \"1.5 USD BRL\"\n");

$converter = new CurrencyConverter(new JsonFile, new Converter, new PrintAmount, 'currencies.json');
$converter->run($argv[2], $argv[3], $argv[1]);
echo $converter->getNewAmount()->getAmount()."\n";